# Generated by Django 2.0 on 2018-06-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='answer',
            field=models.CharField(default='Yes', max_length=10),
            preserve_default=False,
        ),
    ]
